"""Report renderer tests (markdown + rich)."""

from slither_chat import report
from slither_chat.models import AuditResult
from slither_chat.parser import normalize
from slither_chat.rule_backend import enrich
from tests.conftest import EXAMPLES, load_fixture

_SRC = EXAMPLES / "vault.sol"


def _enriched():
    result = normalize(load_fixture("slither_vault.json"), _SRC)
    enrich(result, _SRC)
    return result


def test_markdown_structure():
    md = report.render_markdown(_enriched())
    assert "# Audit report:" in md
    assert "## Summary" in md
    assert "| High |" in md
    assert "## Findings" in md
    assert "reentrancy-eth" in md
    assert "checks-effects-interactions" in md  # explanation rendered
    assert "suggested patch" in md.lower() or "```diff" in md
    assert "Generated by" in md


def test_markdown_sorting_severity_first():
    md = report.render_markdown(_enriched())
    high_idx = md.find("reentrancy-eth")
    info_idx = md.find("solc-version")
    assert high_idx < info_idx


def test_rich_render_no_crash():
    from rich.console import Console

    console = Console(width=100, force_terminal=False, file=None)
    report.render_rich(_enriched(), console)  # must not raise


def test_svg_export_valid_xml(tmp_path):
    import xml.etree.ElementTree as ET

    out = tmp_path / "usage.svg"
    report.render_svg(_enriched(), out)
    assert out.exists()
    data = out.read_text()
    ET.fromstring(data)  # must be well-formed XML
    assert "<svg" in data


def test_empty_report():
    result = AuditResult(source_path="x.sol")
    md = report.render_markdown(result)
    assert "0" in md


def test_plain_report_helper():
    from slither_chat.cli import _plain_report

    text = _plain_report(_enriched())
    assert "reentrancy-eth" in text
    assert "[High]" in text