"""Report renderers: markdown file and rich (terminal / SVG export)."""

from __future__ import annotations

import textwrap
from pathlib import Path

from rich.console import Console, Group
from rich.panel import Panel
from rich.rule import Rule
from rich.syntax import Syntax
from rich.table import Table

from .models import AuditResult, Finding, SEVERITY_ORDER

_SEV_STYLE = {
    "High": "bold red",
    "Medium": "bold yellow",
    "Low": "bold blue",
    "Informational": "dim",
}


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------
def render_markdown(result: AuditResult) -> str:
    counts = result.by_severity()
    lines = [
        f"# Audit report: `{result.source_path}`",
        "",
        f"- **Slither**: {result.slither_version or 'n/a'} "
        f"({result.compiler or 'compiler n/a'})",
        f"- **Backend**: `{result.backend}`",
        f"- **Duration**: {result.duration_sec:.1f}s",
        f"- **Findings**: {len(result.findings)} "
        f"(high={counts['High']}, medium={counts['Medium']}, "
        f"low={counts['Low']}, info={counts['Informational']})",
        "",
        "## Summary",
        "",
        "| Severity | Count |",
        "| --- | --- |",
    ]
    for sev in SEVERITY_ORDER:
        lines.append(f"| {sev.value} | {counts[sev.value]} |")
    lines += ["", "## Findings", ""]

    for i, f in enumerate(result.sorted(), 1):
        lines += _finding_markdown(i, f)

    if result.warnings:
        lines += ["---", "## Slither warnings", ""]
        for w in result.warnings[:8]:
            lines.append(f"- {w}")

    lines += [
        "",
        "---",
        "_Generated by [slither-chat](https://github.com/pxlcrtiv/slither-chat). "
        "Suggested patches are review aids, not autonomous fixes._",
        "",
    ]
    return "\n".join(lines)


def _finding_markdown(i: int, f: Finding) -> list[str]:
    tag = ""
    if f.issue_class:
        tag = f" · **HF class**: {f.issue_class} (conf {f.class_confidence:.2f})"
    out = [
        f"### {i}. `{f.rule_id}` — {f.severity.value}",
        "",
        f"**Where**: {f.location} (lines {', '.join(map(str, f.lines)) or '-'})"
        f" · **Confidence**: {f.confidence or '-'}{tag}",
        "",
        f"**Detector**: {f.description or '-'}",
        "",
    ]
    if f.explanation:
        out += ["**Explanation**:", "", textwrap.dedent(f.explanation), ""]
    if f.fix:
        out += ["**Suggested fix**:", "", textwrap.dedent(f.fix), ""]
    if f.code:
        out += ["**Flagged code**:", "", "```solidity", f.code, "```", ""]
    if f.patch:
        out += ["**Suggested patch (review before applying)**:", "", "```diff", f.patch, "```", ""]
    return out


# ---------------------------------------------------------------------------
# Rich (terminal + SVG export for docs/)
# ---------------------------------------------------------------------------
def build_rich_console(record: bool = False, width: int = 110) -> Console:
    return Console(record=record, width=width, force_terminal=True)


def render_rich(result: AuditResult, console: Console) -> None:
    counts = result.by_severity()
    header = Table.grid(padding=(0, 1))
    header.add_column(justify="right")
    header.add_column()
    header.add_row("[bold]Source[/bold]", str(result.source_path))
    header.add_row("[bold]Slither[/bold]", result.slither_version or "n/a")
    header.add_row("[bold]Backend[/bold]", result.backend)
    header.add_row(
        "[bold]Findings[/bold]",
        f"{len(result.findings)} — "
        + " · ".join(
            f"[{_SEV_STYLE[s.value]}]{s.value}: {counts[s.value]}[/]"
            for s in SEVERITY_ORDER
        ),
    )
    console.print(Panel(header, title="[bold]slither-chat audit[/]", border_style="cyan"))
    console.print()

    summary = Table(title="Summary", show_header=True, header_style="bold")
    for col in ("Severity", "Count"):
        summary.add_column(col)
    for sev in SEVERITY_ORDER:
        summary.add_row(f"[{_SEV_STYLE[sev.value]}]{sev.value}[/]", str(counts[sev.value]))
    console.print(summary)
    console.print()

    for i, f in enumerate(result.sorted(), 1):
        console.print(Rule(f"[bold]#{i} {f.rule_id}[/] [{_SEV_STYLE[f.severity.value]}]{f.severity.value}[/]", style="grey37"))
        tag = f" · [cyan]{f.issue_class} ({f.class_confidence:.2f})[/]" if f.issue_class else ""
        console.print(
            f"[bold]Where:[/] {f.location} · lines {', '.join(map(str, f.lines)) or '-'}"
            f" · confidence {f.confidence or '-'}{tag}"
        )
        console.print(f"[dim]{f.description or ''}[/]")
        if f.explanation:
            console.print(Group("", f"[bold]Explanation:[/] {f.explanation}"))
        if f.fix:
            console.print(f"[bold]Suggested fix:[/] {f.fix}")
        if f.code:
            console.print()
            console.print(Syntax(f.code, "solidity", theme="monokai", line_numbers=False))
        if f.patch:
            console.print()
            console.print(Syntax(f.patch, "diff", theme="monokai"))
        console.print()


def render_svg(result: AuditResult, out_path: str | Path) -> None:
    """Render the report to an SVG file (rich record mode) for docs/."""
    console = build_rich_console(record=True)
    render_rich(result, console)
    console.save_svg(str(out_path), title="slither-chat audit")